### ISSUE TITLE
Chromium Browser

### ISSUE THREAD

**Issue by ghost** [TomFreudenberg/preziplayer#1]
Hi!!, THANK YOU VERY MUCH for this tool, you safe my life, because i had a presentation in the university and i was trying run Presi in debian and ubuntu distros.

The app is  very good, but i had a little problem, my default browser is Chromium and when i selected open browser action, Chromium downloaded presentation.swf, not open http://localhost/12345

I solved this using Firefox, but... why don't run with Chromium?.

I hope you have in mind.

Thank for everything again.

(Sorry for my bad english)

**Comment by dlevison** [comment]
I have the same problem.
If you go to: http://get.adobe.com/flashplayer/otherversions/
You will see there is no flash player for chrome if you choose Linux 64 bit and Ubuntu, only FireFox.

BTW, works great in FireFox, 10x.

**Comment by TomFreudenberg** [comment]
Hi Carlos, first of all, sorry for my late answer. I had not get the issue by mail, have to check my project settings.

I checked your issue for the last and I think I have found a good solution. This will require an update to my repo but I am in a hurry by now. I will add a generic html file named presentation.html in root directory where the link to presentation.swf is also created. Source of html is:

<pre>
&lt;html>
  &lt;head><title>prezi player - offline presentation</title></head>
  &lt;body>
    &lt;object data="presentation.swf" type="application/x-shockwave-flash" id="prezi" width="100%" height="98%"
            style="visibility: visible; width: 100%; height: 98%; left: auto; top: auto; margin: 0 auto;"
    />
  &lt;/body>
&lt;/html>
</pre>


This will be fixed next week.

Thanks and regards
Tom

**Comment by TomFreudenberg** [comment]
Thanx for marking this problem. Its is fixed now (since release 1.0-2) by an additional html index file. I have tested this with following browsers: firefox (3.6.24), chromium (14.0.835.202) and opera (11.52).
