### ISSUE TITLE
mktemp: unrecognized option '--suffix=.prezi' 

### ISSUE THREAD

**Issue by shaunn** [TomFreudenberg/preziplayer#2]
I would love to try out preziplayer, but it fails with the following error after attempting to open the zip file:

Window: "Sorry, could not create TMP directory"

Console:
mktemp: unrecognized option '--suffix=.prezi'

I am using mktemp v7.4 on Ubuntu 10.04.

**Comment by TomFreudenberg** [comment]
Could you please paste the short help in here:

mktemp --help

At least prefix is not important, just easier to identify the created stuff in tmp.

**Comment by TomFreudenberg** [comment]
Ok, I fixed this by later renaming the created temp

<code>__mktemp() {
  # generate a random temp directory 
  PREZI_TMP=$(mktemp -q -d)
  if [[ ! "$?" -eq 0 ]]; then
    __error 1 'Sorry, could not create TMP directory.'
  fi;

  # in case that option --suffix to mktemp is not available overall
  # we do an informal renaming by ourself
  TMP_RENAME=$(mv "${PREZI_TMP}" "${PREZI_TMP}.prezi)"

  # save the new tmp location after successful renaming
  if [[ "$?" -eq 0 ]]; then
    PREZI_TMP="${PREZI_TMP}.prezi"
  fi
}</code>

**Comment by TomFreudenberg** [comment]
Fixed in Release 1.0-4

**Comment by shaunn** [comment]
Confirmed fixed. Thanks!!
