### ISSUE TITLE
Problem with the loop at Chrominium

### ISSUE THREAD

**Issue by Equalibrium** [TomFreudenberg/preziplayer#3]
Hey,

First at all thank you for this amazing player.

Even if I click OK after the presentation, shrink .zip or close, then the player starts a loop, it closes and open automatic.

**Comment by TomFreudenberg** [comment]
Hi, it sounds, that zenity has changed some result codes in 12.04. I will move and test on 12.04.

Thanx for Feedback

**Comment by TomFreudenberg** [comment]
Yes, zenity has changed something, so function __menu() must be updated.

The if statement

<code>if [[ "$?" -eq 0 ]]; then</code>

should be

<code>if [[ -n "${OPTION}" ]]; then</code>

**Comment by TomFreudenberg** [comment]
Hi Equalibrium, please check for issue on launching chromium at

https://github.com/TomFreudenberg/preziplayer/issues/4

**Comment by TomFreudenberg** [comment]
Fixed by Release 1.0-4
