### ISSUE TITLE
Ubuntu 12.04 - Chromium will not launch

### ISSUE THREAD

**Issue by TomFreudenberg** [TomFreudenberg/preziplayer#4]
I have an issue with the Chrominium v. 18.0.1025.151 (Build 130497 Linux) at Ubuntu 12.04

The browser will not open when I click on open presentation. I opened the Chrominium manually, typed http://localhost:12345 - OK, it works.

(This was originally reported by: https://github.com/Equalibrium)

**Comment by TomFreudenberg** [comment]
Hi Equalibrium,

please try once and enter to command-line:

xdg-open http://localhost:12345

and see whats happen and try next:

x-www-browser http://localhost:12345

Thanx for reporting

**Comment by TomFreudenberg** [comment]
Please check also discussion on:

http://www.linuxquestions.org/questions/programming-9/xdg-open-no-method-available-for-opening-889242/

and take a look at the last comment.

**Comment by TomFreudenberg** [comment]
I tried to do an improvement by launching "x-www-browser" when available before using "xdg-open".

Please report any resulting bugs if there are some.

<code>
__open_browser() {
  # build URI
  URI="http://localhost:${WEB_PORT}"

  # info message
  __info "Your browser will now be directed to your offline presentation.\nLaunching ${URI}.\n\nPlease click OK and look at your browser."

  # check method to launch browser
  CMD_OPTION=$(which x-www-browser)

  if [[ "$?" -eq 0 ]]; then
    # on Debian / alternative based systems call x-www-browser
    x-www-browser "${URI}"
  else
    # start defaut web browser on freedesktop systems
    xdg-open "${URI}"
  fi
}
</code>

**Comment by TomFreudenberg** [comment]
Include in Release 1.0-4

**Comment by ccfiel** [comment]
There is no place to thanks you. So I just hijack this thread :D Thanks a lot for this tool!!!
