### ISSUE TITLE
Fullscreen button inside prezi presentation does not work

### ISSUE THREAD

**Issue by TomFreudenberg** [TomFreudenberg/preziplayer#5]
Hi Tom

The 'fullscreen' button to the prezi within my browser (chrome) doesn't seem to work. Any ideas why?
The workaround to this for me is to hit F11 and maximize my browser for now.

Thanks for a great ubuntu fix otherwise!!

See original comment at:
http://prezi.com/5w9yvnnzmnir/prezi-player-on-linux/#comment_785000

**Comment by TomFreudenberg** [comment]
I checked this issue and found that the object of the prezi player should be initialized with several params and values. So I wrote a new html template and implement the player like this:

> <object id="prezi" width="100%" height="100%" style="visibility: visible; width: 100%; height: 100%; left: auto; top: auto; margin: 0 auto;" &gt;
> &nbsp;&nbsp;<embed id="preziobj" width="100%" height="100%" flashvars="aspect-ratio-guide" bgcolor="#ffffff" 
> &nbsp;&nbsp;&nbsp;&nbsp;allowscriptaccess="always" allowfullscreeninteractive="true" allowfullscreen="true" 
> &nbsp;&nbsp;&nbsp;&nbsp;type="application/x-shockwave-flash" src="/presentation.swf" /&gt;
> </object&gt;

I also added some css styling to get a nicer template.

Hope everyone will like it :-)

Tom

P.S.: Finally I attached a favicon from prezi.com and darkened it, so that you will find the "offline" prezzis.

**Comment by TomFreudenberg** [comment]
Included in release 1.0-5

**Comment by angadhn** [comment]
Thanks for the fix! It works splendidly!
